// Code generated by ent, DO NOT EDIT.

package mediaasset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Godspower-Eze/infoai-backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldID, id))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldPosition, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOwnerID, v))
}

// PostItemID applies equality check predicate on the "post_item_id" field. It's identical to PostItemIDEQ.
func PostItemID(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldPostItemID, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldStorageKey, v))
}

// OriginalFilename applies equality check predicate on the "original_filename" field. It's identical to OriginalFilenameEQ.
func OriginalFilename(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOriginalFilename, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSizeBytes, v))
}

// Sha256Checksum applies equality check predicate on the "sha256_checksum" field. It's identical to Sha256ChecksumEQ.
func Sha256Checksum(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSha256Checksum, v))
}

// AltText applies equality check predicate on the "alt_text" field. It's identical to AltTextEQ.
func AltText(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAltText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldPosition, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldOwnerID, vs...))
}

// PostItemIDEQ applies the EQ predicate on the "post_item_id" field.
func PostItemIDEQ(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldPostItemID, v))
}

// PostItemIDNEQ applies the NEQ predicate on the "post_item_id" field.
func PostItemIDNEQ(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldPostItemID, v))
}

// PostItemIDIn applies the In predicate on the "post_item_id" field.
func PostItemIDIn(vs ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldPostItemID, vs...))
}

// PostItemIDNotIn applies the NotIn predicate on the "post_item_id" field.
func PostItemIDNotIn(vs ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldPostItemID, vs...))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldStorageKey, v))
}

// OriginalFilenameEQ applies the EQ predicate on the "original_filename" field.
func OriginalFilenameEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOriginalFilename, v))
}

// OriginalFilenameNEQ applies the NEQ predicate on the "original_filename" field.
func OriginalFilenameNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldOriginalFilename, v))
}

// OriginalFilenameIn applies the In predicate on the "original_filename" field.
func OriginalFilenameIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldOriginalFilename, vs...))
}

// OriginalFilenameNotIn applies the NotIn predicate on the "original_filename" field.
func OriginalFilenameNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldOriginalFilename, vs...))
}

// OriginalFilenameGT applies the GT predicate on the "original_filename" field.
func OriginalFilenameGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldOriginalFilename, v))
}

// OriginalFilenameGTE applies the GTE predicate on the "original_filename" field.
func OriginalFilenameGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldOriginalFilename, v))
}

// OriginalFilenameLT applies the LT predicate on the "original_filename" field.
func OriginalFilenameLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldOriginalFilename, v))
}

// OriginalFilenameLTE applies the LTE predicate on the "original_filename" field.
func OriginalFilenameLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldOriginalFilename, v))
}

// OriginalFilenameContains applies the Contains predicate on the "original_filename" field.
func OriginalFilenameContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldOriginalFilename, v))
}

// OriginalFilenameHasPrefix applies the HasPrefix predicate on the "original_filename" field.
func OriginalFilenameHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldOriginalFilename, v))
}

// OriginalFilenameHasSuffix applies the HasSuffix predicate on the "original_filename" field.
func OriginalFilenameHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldOriginalFilename, v))
}

// OriginalFilenameEqualFold applies the EqualFold predicate on the "original_filename" field.
func OriginalFilenameEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldOriginalFilename, v))
}

// OriginalFilenameContainsFold applies the ContainsFold predicate on the "original_filename" field.
func OriginalFilenameContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldOriginalFilename, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldMimeType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldSizeBytes, v))
}

// Sha256ChecksumEQ applies the EQ predicate on the "sha256_checksum" field.
func Sha256ChecksumEQ(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSha256Checksum, v))
}

// Sha256ChecksumNEQ applies the NEQ predicate on the "sha256_checksum" field.
func Sha256ChecksumNEQ(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldSha256Checksum, v))
}

// Sha256ChecksumIn applies the In predicate on the "sha256_checksum" field.
func Sha256ChecksumIn(vs ...[]byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldSha256Checksum, vs...))
}

// Sha256ChecksumNotIn applies the NotIn predicate on the "sha256_checksum" field.
func Sha256ChecksumNotIn(vs ...[]byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldSha256Checksum, vs...))
}

// Sha256ChecksumGT applies the GT predicate on the "sha256_checksum" field.
func Sha256ChecksumGT(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldSha256Checksum, v))
}

// Sha256ChecksumGTE applies the GTE predicate on the "sha256_checksum" field.
func Sha256ChecksumGTE(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldSha256Checksum, v))
}

// Sha256ChecksumLT applies the LT predicate on the "sha256_checksum" field.
func Sha256ChecksumLT(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldSha256Checksum, v))
}

// Sha256ChecksumLTE applies the LTE predicate on the "sha256_checksum" field.
func Sha256ChecksumLTE(v []byte) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldSha256Checksum, v))
}

// AltTextEQ applies the EQ predicate on the "alt_text" field.
func AltTextEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAltText, v))
}

// AltTextNEQ applies the NEQ predicate on the "alt_text" field.
func AltTextNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldAltText, v))
}

// AltTextIn applies the In predicate on the "alt_text" field.
func AltTextIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldAltText, vs...))
}

// AltTextNotIn applies the NotIn predicate on the "alt_text" field.
func AltTextNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldAltText, vs...))
}

// AltTextGT applies the GT predicate on the "alt_text" field.
func AltTextGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldAltText, v))
}

// AltTextGTE applies the GTE predicate on the "alt_text" field.
func AltTextGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldAltText, v))
}

// AltTextLT applies the LT predicate on the "alt_text" field.
func AltTextLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldAltText, v))
}

// AltTextLTE applies the LTE predicate on the "alt_text" field.
func AltTextLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldAltText, v))
}

// AltTextContains applies the Contains predicate on the "alt_text" field.
func AltTextContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldAltText, v))
}

// AltTextHasPrefix applies the HasPrefix predicate on the "alt_text" field.
func AltTextHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldAltText, v))
}

// AltTextHasSuffix applies the HasSuffix predicate on the "alt_text" field.
func AltTextHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldAltText, v))
}

// AltTextIsNil applies the IsNil predicate on the "alt_text" field.
func AltTextIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldAltText))
}

// AltTextNotNil applies the NotNil predicate on the "alt_text" field.
func AltTextNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldAltText))
}

// AltTextEqualFold applies the EqualFold predicate on the "alt_text" field.
func AltTextEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldAltText, v))
}

// AltTextContainsFold applies the ContainsFold predicate on the "alt_text" field.
func AltTextContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldAltText, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.MediaAsset {
	return predicate.MediaAsset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.MediaAsset {
	return predicate.MediaAsset(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPostItem applies the HasEdge predicate on the "post_item" edge.
func HasPostItem() predicate.MediaAsset {
	return predicate.MediaAsset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostItemTable, PostItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostItemWith applies the HasEdge predicate on the "post_item" edge with a given conditions (other predicates).
func HasPostItemWith(preds ...predicate.PostItem) predicate.MediaAsset {
	return predicate.MediaAsset(func(s *sql.Selector) {
		step := newPostItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.NotPredicates(p))
}
