// Code generated by ent, DO NOT EDIT.

package xaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/godspowere/infoai-backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldID, id))
}

// XUserID applies equality check predicate on the "x_user_id" field. It's identical to XUserIDEQ.
func XUserID(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldXUserID, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldUsername, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldDisplayName, v))
}

// ProfileImageURL applies equality check predicate on the "profile_image_url" field. It's identical to ProfileImageURLEQ.
func ProfileImageURL(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldProfileImageURL, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldRefreshToken, v))
}

// TokenExpiry applies equality check predicate on the "token_expiry" field. It's identical to TokenExpiryEQ.
func TokenExpiry(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldTokenExpiry, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// XUserIDEQ applies the EQ predicate on the "x_user_id" field.
func XUserIDEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldXUserID, v))
}

// XUserIDNEQ applies the NEQ predicate on the "x_user_id" field.
func XUserIDNEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldXUserID, v))
}

// XUserIDIn applies the In predicate on the "x_user_id" field.
func XUserIDIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldXUserID, vs...))
}

// XUserIDNotIn applies the NotIn predicate on the "x_user_id" field.
func XUserIDNotIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldXUserID, vs...))
}

// XUserIDGT applies the GT predicate on the "x_user_id" field.
func XUserIDGT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldXUserID, v))
}

// XUserIDGTE applies the GTE predicate on the "x_user_id" field.
func XUserIDGTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldXUserID, v))
}

// XUserIDLT applies the LT predicate on the "x_user_id" field.
func XUserIDLT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldXUserID, v))
}

// XUserIDLTE applies the LTE predicate on the "x_user_id" field.
func XUserIDLTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldXUserID, v))
}

// XUserIDContains applies the Contains predicate on the "x_user_id" field.
func XUserIDContains(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContains(FieldXUserID, v))
}

// XUserIDHasPrefix applies the HasPrefix predicate on the "x_user_id" field.
func XUserIDHasPrefix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasPrefix(FieldXUserID, v))
}

// XUserIDHasSuffix applies the HasSuffix predicate on the "x_user_id" field.
func XUserIDHasSuffix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasSuffix(FieldXUserID, v))
}

// XUserIDEqualFold applies the EqualFold predicate on the "x_user_id" field.
func XUserIDEqualFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEqualFold(FieldXUserID, v))
}

// XUserIDContainsFold applies the ContainsFold predicate on the "x_user_id" field.
func XUserIDContainsFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContainsFold(FieldXUserID, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContainsFold(FieldUsername, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContainsFold(FieldDisplayName, v))
}

// ProfileImageURLEQ applies the EQ predicate on the "profile_image_url" field.
func ProfileImageURLEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldProfileImageURL, v))
}

// ProfileImageURLNEQ applies the NEQ predicate on the "profile_image_url" field.
func ProfileImageURLNEQ(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldProfileImageURL, v))
}

// ProfileImageURLIn applies the In predicate on the "profile_image_url" field.
func ProfileImageURLIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldProfileImageURL, vs...))
}

// ProfileImageURLNotIn applies the NotIn predicate on the "profile_image_url" field.
func ProfileImageURLNotIn(vs ...string) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldProfileImageURL, vs...))
}

// ProfileImageURLGT applies the GT predicate on the "profile_image_url" field.
func ProfileImageURLGT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldProfileImageURL, v))
}

// ProfileImageURLGTE applies the GTE predicate on the "profile_image_url" field.
func ProfileImageURLGTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldProfileImageURL, v))
}

// ProfileImageURLLT applies the LT predicate on the "profile_image_url" field.
func ProfileImageURLLT(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldProfileImageURL, v))
}

// ProfileImageURLLTE applies the LTE predicate on the "profile_image_url" field.
func ProfileImageURLLTE(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldProfileImageURL, v))
}

// ProfileImageURLContains applies the Contains predicate on the "profile_image_url" field.
func ProfileImageURLContains(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContains(FieldProfileImageURL, v))
}

// ProfileImageURLHasPrefix applies the HasPrefix predicate on the "profile_image_url" field.
func ProfileImageURLHasPrefix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasPrefix(FieldProfileImageURL, v))
}

// ProfileImageURLHasSuffix applies the HasSuffix predicate on the "profile_image_url" field.
func ProfileImageURLHasSuffix(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldHasSuffix(FieldProfileImageURL, v))
}

// ProfileImageURLIsNil applies the IsNil predicate on the "profile_image_url" field.
func ProfileImageURLIsNil() predicate.XAccount {
	return predicate.XAccount(sql.FieldIsNull(FieldProfileImageURL))
}

// ProfileImageURLNotNil applies the NotNil predicate on the "profile_image_url" field.
func ProfileImageURLNotNil() predicate.XAccount {
	return predicate.XAccount(sql.FieldNotNull(FieldProfileImageURL))
}

// ProfileImageURLEqualFold applies the EqualFold predicate on the "profile_image_url" field.
func ProfileImageURLEqualFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldEqualFold(FieldProfileImageURL, v))
}

// ProfileImageURLContainsFold applies the ContainsFold predicate on the "profile_image_url" field.
func ProfileImageURLContainsFold(v string) predicate.XAccount {
	return predicate.XAccount(sql.FieldContainsFold(FieldProfileImageURL, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...[]byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...[]byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...[]byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...[]byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v []byte) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.XAccount {
	return predicate.XAccount(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.XAccount {
	return predicate.XAccount(sql.FieldNotNull(FieldRefreshToken))
}

// TokenExpiryEQ applies the EQ predicate on the "token_expiry" field.
func TokenExpiryEQ(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldTokenExpiry, v))
}

// TokenExpiryNEQ applies the NEQ predicate on the "token_expiry" field.
func TokenExpiryNEQ(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldTokenExpiry, v))
}

// TokenExpiryIn applies the In predicate on the "token_expiry" field.
func TokenExpiryIn(vs ...time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldTokenExpiry, vs...))
}

// TokenExpiryNotIn applies the NotIn predicate on the "token_expiry" field.
func TokenExpiryNotIn(vs ...time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldTokenExpiry, vs...))
}

// TokenExpiryGT applies the GT predicate on the "token_expiry" field.
func TokenExpiryGT(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldTokenExpiry, v))
}

// TokenExpiryGTE applies the GTE predicate on the "token_expiry" field.
func TokenExpiryGTE(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldTokenExpiry, v))
}

// TokenExpiryLT applies the LT predicate on the "token_expiry" field.
func TokenExpiryLT(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldTokenExpiry, v))
}

// TokenExpiryLTE applies the LTE predicate on the "token_expiry" field.
func TokenExpiryLTE(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldTokenExpiry, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.XAccount {
	return predicate.XAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.XAccount {
	return predicate.XAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.XAccount {
	return predicate.XAccount(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.XAccount) predicate.XAccount {
	return predicate.XAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.XAccount) predicate.XAccount {
	return predicate.XAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.XAccount) predicate.XAccount {
	return predicate.XAccount(sql.NotPredicates(p))
}
