// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/mediaasset"
	"github.com/Godspower-Eze/infoai-backend/ent/postitem"
	"github.com/Godspower-Eze/infoai-backend/ent/user"
	"github.com/google/uuid"
)

// MediaAssetCreate is the builder for creating a MediaAsset entity.
type MediaAssetCreate struct {
	config
	mutation *MediaAssetMutation
	hooks    []Hook
}

// SetPosition sets the "position" field.
func (_c *MediaAssetCreate) SetPosition(v int) *MediaAssetCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *MediaAssetCreate) SetOwnerID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetPostItemID sets the "post_item_id" field.
func (_c *MediaAssetCreate) SetPostItemID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetPostItemID(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *MediaAssetCreate) SetStorageKey(v string) *MediaAssetCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetOriginalFilename sets the "original_filename" field.
func (_c *MediaAssetCreate) SetOriginalFilename(v string) *MediaAssetCreate {
	_c.mutation.SetOriginalFilename(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *MediaAssetCreate) SetMimeType(v string) *MediaAssetCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *MediaAssetCreate) SetSizeBytes(v int64) *MediaAssetCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetSha256Checksum sets the "sha256_checksum" field.
func (_c *MediaAssetCreate) SetSha256Checksum(v []byte) *MediaAssetCreate {
	_c.mutation.SetSha256Checksum(v)
	return _c
}

// SetAltText sets the "alt_text" field.
func (_c *MediaAssetCreate) SetAltText(v string) *MediaAssetCreate {
	_c.mutation.SetAltText(v)
	return _c
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableAltText(v *string) *MediaAssetCreate {
	if v != nil {
		_c.SetAltText(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaAssetCreate) SetCreatedAt(v time.Time) *MediaAssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableCreatedAt(v *time.Time) *MediaAssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaAssetCreate) SetID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableID(v *uuid.UUID) *MediaAssetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *MediaAssetCreate) SetOwner(v *User) *MediaAssetCreate {
	return _c.SetOwnerID(v.ID)
}

// SetPostItem sets the "post_item" edge to the PostItem entity.
func (_c *MediaAssetCreate) SetPostItem(v *PostItem) *MediaAssetCreate {
	return _c.SetPostItemID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_c *MediaAssetCreate) Mutation() *MediaAssetMutation {
	return _c.mutation
}

// Save creates the MediaAsset in the database.
func (_c *MediaAssetCreate) Save(ctx context.Context) (*MediaAsset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaAssetCreate) SaveX(ctx context.Context) *MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaAssetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediaasset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mediaasset.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaAssetCreate) check() error {
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "MediaAsset.position"`)}
	}
	if v, ok := _c.mutation.Position(); ok {
		if err := mediaasset.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.position": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "MediaAsset.owner_id"`)}
	}
	if _, ok := _c.mutation.PostItemID(); !ok {
		return &ValidationError{Name: "post_item_id", err: errors.New(`ent: missing required field "MediaAsset.post_item_id"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "MediaAsset.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := mediaasset.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalFilename(); !ok {
		return &ValidationError{Name: "original_filename", err: errors.New(`ent: missing required field "MediaAsset.original_filename"`)}
	}
	if v, ok := _c.mutation.OriginalFilename(); ok {
		if err := mediaasset.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.original_filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "MediaAsset.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := mediaasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "MediaAsset.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := mediaasset.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256Checksum(); !ok {
		return &ValidationError{Name: "sha256_checksum", err: errors.New(`ent: missing required field "MediaAsset.sha256_checksum"`)}
	}
	if v, ok := _c.mutation.Sha256Checksum(); ok {
		if err := mediaasset.Sha256ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "sha256_checksum", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.sha256_checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaAsset.created_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "MediaAsset.owner"`)}
	}
	if len(_c.mutation.PostItemIDs()) == 0 {
		return &ValidationError{Name: "post_item", err: errors.New(`ent: missing required edge "MediaAsset.post_item"`)}
	}
	return nil
}

func (_c *MediaAssetCreate) sqlSave(ctx context.Context) (*MediaAsset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaAssetCreate) createSpec() (*MediaAsset, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaAsset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaasset.Table, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(mediaasset.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(mediaasset.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.OriginalFilename(); ok {
		_spec.SetField(mediaasset.FieldOriginalFilename, field.TypeString, value)
		_node.OriginalFilename = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Sha256Checksum(); ok {
		_spec.SetField(mediaasset.FieldSha256Checksum, field.TypeBytes, value)
		_node.Sha256Checksum = value
	}
	if value, ok := _c.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
		_node.AltText = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediaasset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.OwnerTable,
			Columns: []string{mediaasset.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PostItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.PostItemTable,
			Columns: []string{mediaasset.PostItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaAssetCreateBulk is the builder for creating many MediaAsset entities in bulk.
type MediaAssetCreateBulk struct {
	config
	err      error
	builders []*MediaAssetCreate
}

// Save creates the MediaAsset entities in the database.
func (_c *MediaAssetCreateBulk) Save(ctx context.Context) ([]*MediaAsset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaAsset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaAssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) SaveX(ctx context.Context) []*MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
