// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/mediaasset"
	"github.com/Godspower-Eze/infoai-backend/ent/postitem"
	"github.com/Godspower-Eze/infoai-backend/ent/predicate"
	"github.com/google/uuid"
)

// PostItemUpdate is the builder for updating PostItem entities.
type PostItemUpdate struct {
	config
	hooks    []Hook
	mutation *PostItemMutation
}

// Where appends a list predicates to the PostItemUpdate builder.
func (_u *PostItemUpdate) Where(ps ...predicate.PostItem) *PostItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPosition sets the "position" field.
func (_u *PostItemUpdate) SetPosition(v int) *PostItemUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *PostItemUpdate) SetNillablePosition(v *int) *PostItemUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *PostItemUpdate) AddPosition(v int) *PostItemUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetText sets the "text" field.
func (_u *PostItemUpdate) SetText(v string) *PostItemUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *PostItemUpdate) SetNillableText(v *string) *PostItemUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetXPostID sets the "x_post_id" field.
func (_u *PostItemUpdate) SetXPostID(v string) *PostItemUpdate {
	_u.mutation.SetXPostID(v)
	return _u
}

// SetNillableXPostID sets the "x_post_id" field if the given value is not nil.
func (_u *PostItemUpdate) SetNillableXPostID(v *string) *PostItemUpdate {
	if v != nil {
		_u.SetXPostID(*v)
	}
	return _u
}

// ClearXPostID clears the value of the "x_post_id" field.
func (_u *PostItemUpdate) ClearXPostID() *PostItemUpdate {
	_u.mutation.ClearXPostID()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostItemUpdate) SetPublishedAt(v time.Time) *PostItemUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostItemUpdate) SetNillablePublishedAt(v *time.Time) *PostItemUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostItemUpdate) ClearPublishedAt() *PostItemUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostItemUpdate) SetUpdatedAt(v time.Time) *PostItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMediaAssetIDs adds the "media_assets" edge to the MediaAsset entity by IDs.
func (_u *PostItemUpdate) AddMediaAssetIDs(ids ...uuid.UUID) *PostItemUpdate {
	_u.mutation.AddMediaAssetIDs(ids...)
	return _u
}

// AddMediaAssets adds the "media_assets" edges to the MediaAsset entity.
func (_u *PostItemUpdate) AddMediaAssets(v ...*MediaAsset) *PostItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMediaAssetIDs(ids...)
}

// Mutation returns the PostItemMutation object of the builder.
func (_u *PostItemUpdate) Mutation() *PostItemMutation {
	return _u.mutation
}

// ClearMediaAssets clears all "media_assets" edges to the MediaAsset entity.
func (_u *PostItemUpdate) ClearMediaAssets() *PostItemUpdate {
	_u.mutation.ClearMediaAssets()
	return _u
}

// RemoveMediaAssetIDs removes the "media_assets" edge to MediaAsset entities by IDs.
func (_u *PostItemUpdate) RemoveMediaAssetIDs(ids ...uuid.UUID) *PostItemUpdate {
	_u.mutation.RemoveMediaAssetIDs(ids...)
	return _u
}

// RemoveMediaAssets removes "media_assets" edges to MediaAsset entities.
func (_u *PostItemUpdate) RemoveMediaAssets(v ...*MediaAsset) *PostItemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMediaAssetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := postitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostItemUpdate) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := postitem.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "PostItem.position": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostItem.post"`)
	}
	return nil
}

func (_u *PostItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postitem.Table, postitem.Columns, sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(postitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(postitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(postitem.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.XPostID(); ok {
		_spec.SetField(postitem.FieldXPostID, field.TypeString, value)
	}
	if _u.mutation.XPostIDCleared() {
		_spec.ClearField(postitem.FieldXPostID, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(postitem.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(postitem.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(postitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MediaAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postitem.MediaAssetsTable,
			Columns: []string{postitem.MediaAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMediaAssetsIDs(); len(nodes) > 0 && !_u.mutation.MediaAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postitem.MediaAssetsTable,
			Columns: []string{postitem.MediaAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postitem.MediaAssetsTable,
			Columns: []string{postitem.MediaAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostItemUpdateOne is the builder for updating a single PostItem entity.
type PostItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostItemMutation
}

// SetPosition sets the "position" field.
func (_u *PostItemUpdateOne) SetPosition(v int) *PostItemUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *PostItemUpdateOne) SetNillablePosition(v *int) *PostItemUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *PostItemUpdateOne) AddPosition(v int) *PostItemUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetText sets the "text" field.
func (_u *PostItemUpdateOne) SetText(v string) *PostItemUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *PostItemUpdateOne) SetNillableText(v *string) *PostItemUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetXPostID sets the "x_post_id" field.
func (_u *PostItemUpdateOne) SetXPostID(v string) *PostItemUpdateOne {
	_u.mutation.SetXPostID(v)
	return _u
}

// SetNillableXPostID sets the "x_post_id" field if the given value is not nil.
func (_u *PostItemUpdateOne) SetNillableXPostID(v *string) *PostItemUpdateOne {
	if v != nil {
		_u.SetXPostID(*v)
	}
	return _u
}

// ClearXPostID clears the value of the "x_post_id" field.
func (_u *PostItemUpdateOne) ClearXPostID() *PostItemUpdateOne {
	_u.mutation.ClearXPostID()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostItemUpdateOne) SetPublishedAt(v time.Time) *PostItemUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostItemUpdateOne) SetNillablePublishedAt(v *time.Time) *PostItemUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostItemUpdateOne) ClearPublishedAt() *PostItemUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostItemUpdateOne) SetUpdatedAt(v time.Time) *PostItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMediaAssetIDs adds the "media_assets" edge to the MediaAsset entity by IDs.
func (_u *PostItemUpdateOne) AddMediaAssetIDs(ids ...uuid.UUID) *PostItemUpdateOne {
	_u.mutation.AddMediaAssetIDs(ids...)
	return _u
}

// AddMediaAssets adds the "media_assets" edges to the MediaAsset entity.
func (_u *PostItemUpdateOne) AddMediaAssets(v ...*MediaAsset) *PostItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMediaAssetIDs(ids...)
}

// Mutation returns the PostItemMutation object of the builder.
func (_u *PostItemUpdateOne) Mutation() *PostItemMutation {
	return _u.mutation
}

// ClearMediaAssets clears all "media_assets" edges to the MediaAsset entity.
func (_u *PostItemUpdateOne) ClearMediaAssets() *PostItemUpdateOne {
	_u.mutation.ClearMediaAssets()
	return _u
}

// RemoveMediaAssetIDs removes the "media_assets" edge to MediaAsset entities by IDs.
func (_u *PostItemUpdateOne) RemoveMediaAssetIDs(ids ...uuid.UUID) *PostItemUpdateOne {
	_u.mutation.RemoveMediaAssetIDs(ids...)
	return _u
}

// RemoveMediaAssets removes "media_assets" edges to MediaAsset entities.
func (_u *PostItemUpdateOne) RemoveMediaAssets(v ...*MediaAsset) *PostItemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMediaAssetIDs(ids...)
}

// Where appends a list predicates to the PostItemUpdate builder.
func (_u *PostItemUpdateOne) Where(ps ...predicate.PostItem) *PostItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostItemUpdateOne) Select(field string, fields ...string) *PostItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostItem entity.
func (_u *PostItemUpdateOne) Save(ctx context.Context) (*PostItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostItemUpdateOne) SaveX(ctx context.Context) *PostItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := postitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostItemUpdateOne) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := postitem.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "PostItem.position": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostItem.post"`)
	}
	return nil
}

func (_u *PostItemUpdateOne) sqlSave(ctx context.Context) (_node *PostItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postitem.Table, postitem.Columns, sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postitem.FieldID)
		for _, f := range fields {
			if !postitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(postitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(postitem.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(postitem.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.XPostID(); ok {
		_spec.SetField(postitem.FieldXPostID, field.TypeString, value)
	}
	if _u.mutation.XPostIDCleared() {
		_spec.ClearField(postitem.FieldXPostID, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(postitem.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(postitem.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(postitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MediaAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postitem.MediaAssetsTable,
			Columns: []string{postitem.MediaAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMediaAssetsIDs(); len(nodes) > 0 && !_u.mutation.MediaAssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postitem.MediaAssetsTable,
			Columns: []string{postitem.MediaAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaAssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   postitem.MediaAssetsTable,
			Columns: []string{postitem.MediaAssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
