// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Godspower-Eze/infoai-backend/ent/post"
	"github.com/Godspower-Eze/infoai-backend/ent/user"
	"github.com/Godspower-Eze/infoai-backend/ent/xaccount"
	"github.com/google/uuid"
)

// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreationMode holds the value of the "creation_mode" field.
	CreationMode post.CreationMode `json:"creation_mode,omitempty"`
	// Status holds the value of the "status" field.
	Status post.Status `json:"status,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// XAccountID holds the value of the "x_account_id" field.
	XAccountID uuid.UUID `json:"x_account_id,omitempty"`
	// ScheduledAt holds the value of the "scheduled_at" field.
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	// PublishRequestedAt holds the value of the "publish_requested_at" field.
	PublishRequestedAt *time.Time `json:"publish_requested_at,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`
	// ActiveRiverJobID holds the value of the "active_river_job_id" field.
	ActiveRiverJobID *int64 `json:"active_river_job_id,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode *string `json:"last_error_code,omitempty"`
	// LastErrorMessage holds the value of the "last_error_message" field.
	LastErrorMessage *string `json:"last_error_message,omitempty"`
	// LeaseToken holds the value of the "lease_token" field.
	LeaseToken *uuid.UUID `json:"lease_token,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner *string `json:"lease_owner,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// LeaseVersion holds the value of the "lease_version" field.
	LeaseVersion int64 `json:"lease_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges        PostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// XAccount holds the value of the x_account edge.
	XAccount *XAccount `json:"x_account,omitempty"`
	// Items holds the value of the items edge.
	Items []*PostItem `json:"items,omitempty"`
	// Attempts holds the value of the attempts edge.
	Attempts []*PublicationAttempt `json:"attempts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// XAccountOrErr returns the XAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) XAccountOrErr() (*XAccount, error) {
	if e.XAccount != nil {
		return e.XAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: xaccount.Label}
	}
	return nil, &NotLoadedError{edge: "x_account"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) ItemsOrErr() ([]*PostItem, error) {
	if e.loadedTypes[2] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// AttemptsOrErr returns the Attempts value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) AttemptsOrErr() ([]*PublicationAttempt, error) {
	if e.loadedTypes[3] {
		return e.Attempts, nil
	}
	return nil, &NotLoadedError{edge: "attempts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Post) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case post.FieldLeaseToken:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case post.FieldActiveRiverJobID, post.FieldAttemptCount, post.FieldLeaseVersion:
			values[i] = new(sql.NullInt64)
		case post.FieldCreationMode, post.FieldStatus, post.FieldLastErrorCode, post.FieldLastErrorMessage, post.FieldLeaseOwner:
			values[i] = new(sql.NullString)
		case post.FieldScheduledAt, post.FieldPublishRequestedAt, post.FieldPublishedAt, post.FieldNextAttemptAt, post.FieldLeaseExpiresAt, post.FieldCreatedAt, post.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case post.FieldID, post.FieldOwnerID, post.FieldXAccountID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Post fields.
func (_m *Post) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case post.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case post.FieldCreationMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creation_mode", values[i])
			} else if value.Valid {
				_m.CreationMode = post.CreationMode(value.String)
			}
		case post.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = post.Status(value.String)
			}
		case post.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case post.FieldXAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field x_account_id", values[i])
			} else if value != nil {
				_m.XAccountID = *value
			}
		case post.FieldScheduledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_at", values[i])
			} else if value.Valid {
				_m.ScheduledAt = new(time.Time)
				*_m.ScheduledAt = value.Time
			}
		case post.FieldPublishRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field publish_requested_at", values[i])
			} else if value.Valid {
				_m.PublishRequestedAt = new(time.Time)
				*_m.PublishRequestedAt = value.Time
			}
		case post.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case post.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = new(time.Time)
				*_m.NextAttemptAt = value.Time
			}
		case post.FieldActiveRiverJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_river_job_id", values[i])
			} else if value.Valid {
				_m.ActiveRiverJobID = new(int64)
				*_m.ActiveRiverJobID = value.Int64
			}
		case post.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case post.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = new(string)
				*_m.LastErrorCode = value.String
			}
		case post.FieldLastErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_message", values[i])
			} else if value.Valid {
				_m.LastErrorMessage = new(string)
				*_m.LastErrorMessage = value.String
			}
		case post.FieldLeaseToken:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field lease_token", values[i])
			} else if value.Valid {
				_m.LeaseToken = new(uuid.UUID)
				*_m.LeaseToken = *value.S.(*uuid.UUID)
			}
		case post.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = new(string)
				*_m.LeaseOwner = value.String
			}
		case post.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case post.FieldLeaseVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lease_version", values[i])
			} else if value.Valid {
				_m.LeaseVersion = value.Int64
			}
		case post.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case post.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Post.
// This includes values selected through modifiers, order, etc.
func (_m *Post) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Post entity.
func (_m *Post) QueryOwner() *UserQuery {
	return NewPostClient(_m.config).QueryOwner(_m)
}

// QueryXAccount queries the "x_account" edge of the Post entity.
func (_m *Post) QueryXAccount() *XAccountQuery {
	return NewPostClient(_m.config).QueryXAccount(_m)
}

// QueryItems queries the "items" edge of the Post entity.
func (_m *Post) QueryItems() *PostItemQuery {
	return NewPostClient(_m.config).QueryItems(_m)
}

// QueryAttempts queries the "attempts" edge of the Post entity.
func (_m *Post) QueryAttempts() *PublicationAttemptQuery {
	return NewPostClient(_m.config).QueryAttempts(_m)
}

// Update returns a builder for updating this Post.
// Note that you need to call Post.Unwrap() before calling this method if this Post
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Post) Update() *PostUpdateOne {
	return NewPostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Post entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Post) Unwrap() *Post {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Post is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Post) String() string {
	var builder strings.Builder
	builder.WriteString("Post(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("creation_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreationMode))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("x_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.XAccountID))
	builder.WriteString(", ")
	if v := _m.ScheduledAt; v != nil {
		builder.WriteString("scheduled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PublishRequestedAt; v != nil {
		builder.WriteString("publish_requested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextAttemptAt; v != nil {
		builder.WriteString("next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ActiveRiverJobID; v != nil {
		builder.WriteString("active_river_job_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	if v := _m.LastErrorCode; v != nil {
		builder.WriteString("last_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorMessage; v != nil {
		builder.WriteString("last_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseToken; v != nil {
		builder.WriteString("lease_token=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LeaseOwner; v != nil {
		builder.WriteString("lease_owner=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("lease_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeaseVersion))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Posts is a parsable slice of Post.
type Posts []*Post
