// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/post"
	"github.com/Godspower-Eze/infoai-backend/ent/postitem"
	"github.com/Godspower-Eze/infoai-backend/ent/predicate"
	"github.com/Godspower-Eze/infoai-backend/ent/publicationattempt"
	"github.com/google/uuid"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreationMode sets the "creation_mode" field.
func (_u *PostUpdate) SetCreationMode(v post.CreationMode) *PostUpdate {
	_u.mutation.SetCreationMode(v)
	return _u
}

// SetNillableCreationMode sets the "creation_mode" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCreationMode(v *post.CreationMode) *PostUpdate {
	if v != nil {
		_u.SetCreationMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdate) SetStatus(v post.Status) *PostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdate) SetNillableStatus(v *post.Status) *PostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *PostUpdate) SetScheduledAt(v time.Time) *PostUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableScheduledAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (_u *PostUpdate) ClearScheduledAt() *PostUpdate {
	_u.mutation.ClearScheduledAt()
	return _u
}

// SetPublishRequestedAt sets the "publish_requested_at" field.
func (_u *PostUpdate) SetPublishRequestedAt(v time.Time) *PostUpdate {
	_u.mutation.SetPublishRequestedAt(v)
	return _u
}

// SetNillablePublishRequestedAt sets the "publish_requested_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishRequestedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPublishRequestedAt(*v)
	}
	return _u
}

// ClearPublishRequestedAt clears the value of the "publish_requested_at" field.
func (_u *PostUpdate) ClearPublishRequestedAt() *PostUpdate {
	_u.mutation.ClearPublishRequestedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdate) SetPublishedAt(v time.Time) *PostUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdate) ClearPublishedAt() *PostUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PostUpdate) SetNextAttemptAt(v time.Time) *PostUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableNextAttemptAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PostUpdate) ClearNextAttemptAt() *PostUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetActiveRiverJobID sets the "active_river_job_id" field.
func (_u *PostUpdate) SetActiveRiverJobID(v int64) *PostUpdate {
	_u.mutation.ResetActiveRiverJobID()
	_u.mutation.SetActiveRiverJobID(v)
	return _u
}

// SetNillableActiveRiverJobID sets the "active_river_job_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableActiveRiverJobID(v *int64) *PostUpdate {
	if v != nil {
		_u.SetActiveRiverJobID(*v)
	}
	return _u
}

// AddActiveRiverJobID adds value to the "active_river_job_id" field.
func (_u *PostUpdate) AddActiveRiverJobID(v int64) *PostUpdate {
	_u.mutation.AddActiveRiverJobID(v)
	return _u
}

// ClearActiveRiverJobID clears the value of the "active_river_job_id" field.
func (_u *PostUpdate) ClearActiveRiverJobID() *PostUpdate {
	_u.mutation.ClearActiveRiverJobID()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *PostUpdate) SetAttemptCount(v int) *PostUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAttemptCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *PostUpdate) AddAttemptCount(v int) *PostUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *PostUpdate) SetLastErrorCode(v string) *PostUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLastErrorCode(v *string) *PostUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *PostUpdate) ClearLastErrorCode() *PostUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *PostUpdate) SetLastErrorMessage(v string) *PostUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLastErrorMessage(v *string) *PostUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *PostUpdate) ClearLastErrorMessage() *PostUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetLeaseToken sets the "lease_token" field.
func (_u *PostUpdate) SetLeaseToken(v uuid.UUID) *PostUpdate {
	_u.mutation.SetLeaseToken(v)
	return _u
}

// SetNillableLeaseToken sets the "lease_token" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLeaseToken(v *uuid.UUID) *PostUpdate {
	if v != nil {
		_u.SetLeaseToken(*v)
	}
	return _u
}

// ClearLeaseToken clears the value of the "lease_token" field.
func (_u *PostUpdate) ClearLeaseToken() *PostUpdate {
	_u.mutation.ClearLeaseToken()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *PostUpdate) SetLeaseOwner(v string) *PostUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLeaseOwner(v *string) *PostUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *PostUpdate) ClearLeaseOwner() *PostUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *PostUpdate) SetLeaseExpiresAt(v time.Time) *PostUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLeaseExpiresAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *PostUpdate) ClearLeaseExpiresAt() *PostUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetLeaseVersion sets the "lease_version" field.
func (_u *PostUpdate) SetLeaseVersion(v int64) *PostUpdate {
	_u.mutation.ResetLeaseVersion()
	_u.mutation.SetLeaseVersion(v)
	return _u
}

// SetNillableLeaseVersion sets the "lease_version" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLeaseVersion(v *int64) *PostUpdate {
	if v != nil {
		_u.SetLeaseVersion(*v)
	}
	return _u
}

// AddLeaseVersion adds value to the "lease_version" field.
func (_u *PostUpdate) AddLeaseVersion(v int64) *PostUpdate {
	_u.mutation.AddLeaseVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddItemIDs adds the "items" edge to the PostItem entity by IDs.
func (_u *PostUpdate) AddItemIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the PostItem entity.
func (_u *PostUpdate) AddItems(v ...*PostItem) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddAttemptIDs adds the "attempts" edge to the PublicationAttempt entity by IDs.
func (_u *PostUpdate) AddAttemptIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the PublicationAttempt entity.
func (_u *PostUpdate) AddAttempts(v ...*PublicationAttempt) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the PostItem entity.
func (_u *PostUpdate) ClearItems() *PostUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to PostItem entities by IDs.
func (_u *PostUpdate) RemoveItemIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to PostItem entities.
func (_u *PostUpdate) RemoveItems(v ...*PostItem) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearAttempts clears all "attempts" edges to the PublicationAttempt entity.
func (_u *PostUpdate) ClearAttempts() *PostUpdate {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to PublicationAttempt entities by IDs.
func (_u *PostUpdate) RemoveAttemptIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to PublicationAttempt entities.
func (_u *PostUpdate) RemoveAttempts(v ...*PublicationAttempt) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.CreationMode(); ok {
		if err := post.CreationModeValidator(v); err != nil {
			return &ValidationError{Name: "creation_mode", err: fmt.Errorf(`ent: validator failed for field "Post.creation_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActiveRiverJobID(); ok {
		if err := post.ActiveRiverJobIDValidator(v); err != nil {
			return &ValidationError{Name: "active_river_job_id", err: fmt.Errorf(`ent: validator failed for field "Post.active_river_job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := post.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "Post.attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := post.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "Post.last_error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorMessage(); ok {
		if err := post.LastErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "last_error_message", err: fmt.Errorf(`ent: validator failed for field "Post.last_error_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := post.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "Post.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseVersion(); ok {
		if err := post.LeaseVersionValidator(v); err != nil {
			return &ValidationError{Name: "lease_version", err: fmt.Errorf(`ent: validator failed for field "Post.lease_version": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.owner"`)
	}
	if _u.mutation.XAccountCleared() && len(_u.mutation.XAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.x_account"`)
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreationMode(); ok {
		_spec.SetField(post.FieldCreationMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(post.FieldScheduledAt, field.TypeTime, value)
	}
	if _u.mutation.ScheduledAtCleared() {
		_spec.ClearField(post.FieldScheduledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishRequestedAt(); ok {
		_spec.SetField(post.FieldPublishRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishRequestedAtCleared() {
		_spec.ClearField(post.FieldPublishRequestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(post.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(post.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActiveRiverJobID(); ok {
		_spec.SetField(post.FieldActiveRiverJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveRiverJobID(); ok {
		_spec.AddField(post.FieldActiveRiverJobID, field.TypeInt64, value)
	}
	if _u.mutation.ActiveRiverJobIDCleared() {
		_spec.ClearField(post.FieldActiveRiverJobID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(post.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(post.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(post.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(post.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(post.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(post.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseToken(); ok {
		_spec.SetField(post.FieldLeaseToken, field.TypeUUID, value)
	}
	if _u.mutation.LeaseTokenCleared() {
		_spec.ClearField(post.FieldLeaseToken, field.TypeUUID)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(post.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(post.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(post.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(post.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LeaseVersion(); ok {
		_spec.SetField(post.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseVersion(); ok {
		_spec.AddField(post.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ItemsTable,
			Columns: []string{post.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ItemsTable,
			Columns: []string{post.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ItemsTable,
			Columns: []string{post.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AttemptsTable,
			Columns: []string{post.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AttemptsTable,
			Columns: []string{post.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AttemptsTable,
			Columns: []string{post.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetCreationMode sets the "creation_mode" field.
func (_u *PostUpdateOne) SetCreationMode(v post.CreationMode) *PostUpdateOne {
	_u.mutation.SetCreationMode(v)
	return _u
}

// SetNillableCreationMode sets the "creation_mode" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCreationMode(v *post.CreationMode) *PostUpdateOne {
	if v != nil {
		_u.SetCreationMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdateOne) SetStatus(v post.Status) *PostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableStatus(v *post.Status) *PostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *PostUpdateOne) SetScheduledAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableScheduledAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (_u *PostUpdateOne) ClearScheduledAt() *PostUpdateOne {
	_u.mutation.ClearScheduledAt()
	return _u
}

// SetPublishRequestedAt sets the "publish_requested_at" field.
func (_u *PostUpdateOne) SetPublishRequestedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetPublishRequestedAt(v)
	return _u
}

// SetNillablePublishRequestedAt sets the "publish_requested_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishRequestedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPublishRequestedAt(*v)
	}
	return _u
}

// ClearPublishRequestedAt clears the value of the "publish_requested_at" field.
func (_u *PostUpdateOne) ClearPublishRequestedAt() *PostUpdateOne {
	_u.mutation.ClearPublishRequestedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdateOne) SetPublishedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdateOne) ClearPublishedAt() *PostUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PostUpdateOne) SetNextAttemptAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableNextAttemptAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PostUpdateOne) ClearNextAttemptAt() *PostUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetActiveRiverJobID sets the "active_river_job_id" field.
func (_u *PostUpdateOne) SetActiveRiverJobID(v int64) *PostUpdateOne {
	_u.mutation.ResetActiveRiverJobID()
	_u.mutation.SetActiveRiverJobID(v)
	return _u
}

// SetNillableActiveRiverJobID sets the "active_river_job_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableActiveRiverJobID(v *int64) *PostUpdateOne {
	if v != nil {
		_u.SetActiveRiverJobID(*v)
	}
	return _u
}

// AddActiveRiverJobID adds value to the "active_river_job_id" field.
func (_u *PostUpdateOne) AddActiveRiverJobID(v int64) *PostUpdateOne {
	_u.mutation.AddActiveRiverJobID(v)
	return _u
}

// ClearActiveRiverJobID clears the value of the "active_river_job_id" field.
func (_u *PostUpdateOne) ClearActiveRiverJobID() *PostUpdateOne {
	_u.mutation.ClearActiveRiverJobID()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *PostUpdateOne) SetAttemptCount(v int) *PostUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAttemptCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *PostUpdateOne) AddAttemptCount(v int) *PostUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *PostUpdateOne) SetLastErrorCode(v string) *PostUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLastErrorCode(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *PostUpdateOne) ClearLastErrorCode() *PostUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *PostUpdateOne) SetLastErrorMessage(v string) *PostUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLastErrorMessage(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *PostUpdateOne) ClearLastErrorMessage() *PostUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetLeaseToken sets the "lease_token" field.
func (_u *PostUpdateOne) SetLeaseToken(v uuid.UUID) *PostUpdateOne {
	_u.mutation.SetLeaseToken(v)
	return _u
}

// SetNillableLeaseToken sets the "lease_token" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLeaseToken(v *uuid.UUID) *PostUpdateOne {
	if v != nil {
		_u.SetLeaseToken(*v)
	}
	return _u
}

// ClearLeaseToken clears the value of the "lease_token" field.
func (_u *PostUpdateOne) ClearLeaseToken() *PostUpdateOne {
	_u.mutation.ClearLeaseToken()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *PostUpdateOne) SetLeaseOwner(v string) *PostUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLeaseOwner(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *PostUpdateOne) ClearLeaseOwner() *PostUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *PostUpdateOne) SetLeaseExpiresAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *PostUpdateOne) ClearLeaseExpiresAt() *PostUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetLeaseVersion sets the "lease_version" field.
func (_u *PostUpdateOne) SetLeaseVersion(v int64) *PostUpdateOne {
	_u.mutation.ResetLeaseVersion()
	_u.mutation.SetLeaseVersion(v)
	return _u
}

// SetNillableLeaseVersion sets the "lease_version" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLeaseVersion(v *int64) *PostUpdateOne {
	if v != nil {
		_u.SetLeaseVersion(*v)
	}
	return _u
}

// AddLeaseVersion adds value to the "lease_version" field.
func (_u *PostUpdateOne) AddLeaseVersion(v int64) *PostUpdateOne {
	_u.mutation.AddLeaseVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddItemIDs adds the "items" edge to the PostItem entity by IDs.
func (_u *PostUpdateOne) AddItemIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the PostItem entity.
func (_u *PostUpdateOne) AddItems(v ...*PostItem) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddAttemptIDs adds the "attempts" edge to the PublicationAttempt entity by IDs.
func (_u *PostUpdateOne) AddAttemptIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddAttemptIDs(ids...)
	return _u
}

// AddAttempts adds the "attempts" edges to the PublicationAttempt entity.
func (_u *PostUpdateOne) AddAttempts(v ...*PublicationAttempt) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttemptIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the PostItem entity.
func (_u *PostUpdateOne) ClearItems() *PostUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to PostItem entities by IDs.
func (_u *PostUpdateOne) RemoveItemIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to PostItem entities.
func (_u *PostUpdateOne) RemoveItems(v ...*PostItem) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearAttempts clears all "attempts" edges to the PublicationAttempt entity.
func (_u *PostUpdateOne) ClearAttempts() *PostUpdateOne {
	_u.mutation.ClearAttempts()
	return _u
}

// RemoveAttemptIDs removes the "attempts" edge to PublicationAttempt entities by IDs.
func (_u *PostUpdateOne) RemoveAttemptIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveAttemptIDs(ids...)
	return _u
}

// RemoveAttempts removes "attempts" edges to PublicationAttempt entities.
func (_u *PostUpdateOne) RemoveAttempts(v ...*PublicationAttempt) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttemptIDs(ids...)
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.CreationMode(); ok {
		if err := post.CreationModeValidator(v); err != nil {
			return &ValidationError{Name: "creation_mode", err: fmt.Errorf(`ent: validator failed for field "Post.creation_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActiveRiverJobID(); ok {
		if err := post.ActiveRiverJobIDValidator(v); err != nil {
			return &ValidationError{Name: "active_river_job_id", err: fmt.Errorf(`ent: validator failed for field "Post.active_river_job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := post.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "Post.attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := post.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "Post.last_error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorMessage(); ok {
		if err := post.LastErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "last_error_message", err: fmt.Errorf(`ent: validator failed for field "Post.last_error_message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := post.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "Post.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseVersion(); ok {
		if err := post.LeaseVersionValidator(v); err != nil {
			return &ValidationError{Name: "lease_version", err: fmt.Errorf(`ent: validator failed for field "Post.lease_version": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.owner"`)
	}
	if _u.mutation.XAccountCleared() && len(_u.mutation.XAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.x_account"`)
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreationMode(); ok {
		_spec.SetField(post.FieldCreationMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(post.FieldScheduledAt, field.TypeTime, value)
	}
	if _u.mutation.ScheduledAtCleared() {
		_spec.ClearField(post.FieldScheduledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishRequestedAt(); ok {
		_spec.SetField(post.FieldPublishRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishRequestedAtCleared() {
		_spec.ClearField(post.FieldPublishRequestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(post.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(post.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActiveRiverJobID(); ok {
		_spec.SetField(post.FieldActiveRiverJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveRiverJobID(); ok {
		_spec.AddField(post.FieldActiveRiverJobID, field.TypeInt64, value)
	}
	if _u.mutation.ActiveRiverJobIDCleared() {
		_spec.ClearField(post.FieldActiveRiverJobID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(post.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(post.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(post.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(post.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(post.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(post.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseToken(); ok {
		_spec.SetField(post.FieldLeaseToken, field.TypeUUID, value)
	}
	if _u.mutation.LeaseTokenCleared() {
		_spec.ClearField(post.FieldLeaseToken, field.TypeUUID)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(post.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(post.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(post.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(post.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LeaseVersion(); ok {
		_spec.SetField(post.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseVersion(); ok {
		_spec.AddField(post.FieldLeaseVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ItemsTable,
			Columns: []string{post.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ItemsTable,
			Columns: []string{post.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ItemsTable,
			Columns: []string{post.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AttemptsTable,
			Columns: []string{post.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttemptsIDs(); len(nodes) > 0 && !_u.mutation.AttemptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AttemptsTable,
			Columns: []string{post.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttemptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AttemptsTable,
			Columns: []string{post.AttemptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
