// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Godspower-Eze/infoai-backend/ent/post"
	"github.com/Godspower-Eze/infoai-backend/ent/postitem"
	"github.com/google/uuid"
)

// PostItem is the model entity for the PostItem schema.
type PostItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID uuid.UUID `json:"post_id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// XPostID holds the value of the "x_post_id" field.
	XPostID *string `json:"x_post_id,omitempty"`
	// SubmissionState holds the value of the "submission_state" field.
	SubmissionState postitem.SubmissionState `json:"submission_state,omitempty"`
	// SubmissionStartedAt holds the value of the "submission_started_at" field.
	SubmissionStartedAt *time.Time `json:"submission_started_at,omitempty"`
	// OutcomeConfirmedAt holds the value of the "outcome_confirmed_at" field.
	OutcomeConfirmedAt *time.Time `json:"outcome_confirmed_at,omitempty"`
	// OutcomeConfirmedBy holds the value of the "outcome_confirmed_by" field.
	OutcomeConfirmedBy *uuid.UUID `json:"outcome_confirmed_by,omitempty"`
	// ConfirmedXPostURL holds the value of the "confirmed_x_post_url" field.
	ConfirmedXPostURL *string `json:"confirmed_x_post_url,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostItemQuery when eager-loading is set.
	Edges        PostItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostItemEdges holds the relations/edges for other nodes in the graph.
type PostItemEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// MediaAssets holds the value of the media_assets edge.
	MediaAssets []*MediaAsset `json:"media_assets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostItemEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// MediaAssetsOrErr returns the MediaAssets value or an error if the edge
// was not loaded in eager-loading.
func (e PostItemEdges) MediaAssetsOrErr() ([]*MediaAsset, error) {
	if e.loadedTypes[1] {
		return e.MediaAssets, nil
	}
	return nil, &NotLoadedError{edge: "media_assets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postitem.FieldOutcomeConfirmedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case postitem.FieldPosition:
			values[i] = new(sql.NullInt64)
		case postitem.FieldText, postitem.FieldXPostID, postitem.FieldSubmissionState, postitem.FieldConfirmedXPostURL:
			values[i] = new(sql.NullString)
		case postitem.FieldSubmissionStartedAt, postitem.FieldOutcomeConfirmedAt, postitem.FieldPublishedAt, postitem.FieldCreatedAt, postitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case postitem.FieldID, postitem.FieldPostID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostItem fields.
func (_m *PostItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case postitem.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case postitem.FieldPostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value != nil {
				_m.PostID = *value
			}
		case postitem.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case postitem.FieldXPostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field x_post_id", values[i])
			} else if value.Valid {
				_m.XPostID = new(string)
				*_m.XPostID = value.String
			}
		case postitem.FieldSubmissionState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field submission_state", values[i])
			} else if value.Valid {
				_m.SubmissionState = postitem.SubmissionState(value.String)
			}
		case postitem.FieldSubmissionStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submission_started_at", values[i])
			} else if value.Valid {
				_m.SubmissionStartedAt = new(time.Time)
				*_m.SubmissionStartedAt = value.Time
			}
		case postitem.FieldOutcomeConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field outcome_confirmed_at", values[i])
			} else if value.Valid {
				_m.OutcomeConfirmedAt = new(time.Time)
				*_m.OutcomeConfirmedAt = value.Time
			}
		case postitem.FieldOutcomeConfirmedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field outcome_confirmed_by", values[i])
			} else if value.Valid {
				_m.OutcomeConfirmedBy = new(uuid.UUID)
				*_m.OutcomeConfirmedBy = *value.S.(*uuid.UUID)
			}
		case postitem.FieldConfirmedXPostURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_x_post_url", values[i])
			} else if value.Valid {
				_m.ConfirmedXPostURL = new(string)
				*_m.ConfirmedXPostURL = value.String
			}
		case postitem.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case postitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case postitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostItem.
// This includes values selected through modifiers, order, etc.
func (_m *PostItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostItem entity.
func (_m *PostItem) QueryPost() *PostQuery {
	return NewPostItemClient(_m.config).QueryPost(_m)
}

// QueryMediaAssets queries the "media_assets" edge of the PostItem entity.
func (_m *PostItem) QueryMediaAssets() *MediaAssetQuery {
	return NewPostItemClient(_m.config).QueryMediaAssets(_m)
}

// Update returns a builder for updating this PostItem.
// Note that you need to call PostItem.Unwrap() before calling this method if this PostItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PostItem) Update() *PostItemUpdateOne {
	return NewPostItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PostItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PostItem) Unwrap() *PostItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PostItem) String() string {
	var builder strings.Builder
	builder.WriteString("PostItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	if v := _m.XPostID; v != nil {
		builder.WriteString("x_post_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("submission_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubmissionState))
	builder.WriteString(", ")
	if v := _m.SubmissionStartedAt; v != nil {
		builder.WriteString("submission_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OutcomeConfirmedAt; v != nil {
		builder.WriteString("outcome_confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OutcomeConfirmedBy; v != nil {
		builder.WriteString("outcome_confirmed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedXPostURL; v != nil {
		builder.WriteString("confirmed_x_post_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PostItems is a parsable slice of PostItem.
type PostItems []*PostItem
