// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/predicate"
	"github.com/Godspower-Eze/infoai-backend/ent/publicationattempt"
)

// PublicationAttemptUpdate is the builder for updating PublicationAttempt entities.
type PublicationAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *PublicationAttemptMutation
}

// Where appends a list predicates to the PublicationAttemptUpdate builder.
func (_u *PublicationAttemptUpdate) Where(ps ...predicate.PublicationAttempt) *PublicationAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *PublicationAttemptUpdate) SetOutcome(v publicationattempt.Outcome) *PublicationAttemptUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableOutcome(v *publicationattempt.Outcome) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetRetryable sets the "retryable" field.
func (_u *PublicationAttemptUpdate) SetRetryable(v bool) *PublicationAttemptUpdate {
	_u.mutation.SetRetryable(v)
	return _u
}

// SetNillableRetryable sets the "retryable" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableRetryable(v *bool) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetRetryable(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *PublicationAttemptUpdate) SetErrorCode(v string) *PublicationAttemptUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableErrorCode(v *string) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *PublicationAttemptUpdate) ClearErrorCode() *PublicationAttemptUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PublicationAttemptUpdate) SetErrorMessage(v string) *PublicationAttemptUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableErrorMessage(v *string) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *PublicationAttemptUpdate) ClearErrorMessage() *PublicationAttemptUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *PublicationAttemptUpdate) SetFinishedAt(v time.Time) *PublicationAttemptUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *PublicationAttemptUpdate) SetNillableFinishedAt(v *time.Time) *PublicationAttemptUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *PublicationAttemptUpdate) ClearFinishedAt() *PublicationAttemptUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the PublicationAttemptMutation object of the builder.
func (_u *PublicationAttemptUpdate) Mutation() *PublicationAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PublicationAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PublicationAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PublicationAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PublicationAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PublicationAttemptUpdate) check() error {
	if v, ok := _u.mutation.Outcome(); ok {
		if err := publicationattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.outcome": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := publicationattempt.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := publicationattempt.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.error_message": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PublicationAttempt.post"`)
	}
	return nil
}

func (_u *PublicationAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(publicationattempt.Table, publicationattempt.Columns, sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(publicationattempt.FieldOutcome, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Retryable(); ok {
		_spec.SetField(publicationattempt.FieldRetryable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(publicationattempt.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(publicationattempt.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(publicationattempt.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(publicationattempt.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(publicationattempt.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(publicationattempt.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publicationattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PublicationAttemptUpdateOne is the builder for updating a single PublicationAttempt entity.
type PublicationAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PublicationAttemptMutation
}

// SetOutcome sets the "outcome" field.
func (_u *PublicationAttemptUpdateOne) SetOutcome(v publicationattempt.Outcome) *PublicationAttemptUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableOutcome(v *publicationattempt.Outcome) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetRetryable sets the "retryable" field.
func (_u *PublicationAttemptUpdateOne) SetRetryable(v bool) *PublicationAttemptUpdateOne {
	_u.mutation.SetRetryable(v)
	return _u
}

// SetNillableRetryable sets the "retryable" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableRetryable(v *bool) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetRetryable(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *PublicationAttemptUpdateOne) SetErrorCode(v string) *PublicationAttemptUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableErrorCode(v *string) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *PublicationAttemptUpdateOne) ClearErrorCode() *PublicationAttemptUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *PublicationAttemptUpdateOne) SetErrorMessage(v string) *PublicationAttemptUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableErrorMessage(v *string) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *PublicationAttemptUpdateOne) ClearErrorMessage() *PublicationAttemptUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *PublicationAttemptUpdateOne) SetFinishedAt(v time.Time) *PublicationAttemptUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *PublicationAttemptUpdateOne) SetNillableFinishedAt(v *time.Time) *PublicationAttemptUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *PublicationAttemptUpdateOne) ClearFinishedAt() *PublicationAttemptUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the PublicationAttemptMutation object of the builder.
func (_u *PublicationAttemptUpdateOne) Mutation() *PublicationAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the PublicationAttemptUpdate builder.
func (_u *PublicationAttemptUpdateOne) Where(ps ...predicate.PublicationAttempt) *PublicationAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PublicationAttemptUpdateOne) Select(field string, fields ...string) *PublicationAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PublicationAttempt entity.
func (_u *PublicationAttemptUpdateOne) Save(ctx context.Context) (*PublicationAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PublicationAttemptUpdateOne) SaveX(ctx context.Context) *PublicationAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PublicationAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PublicationAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PublicationAttemptUpdateOne) check() error {
	if v, ok := _u.mutation.Outcome(); ok {
		if err := publicationattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.outcome": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := publicationattempt.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := publicationattempt.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "PublicationAttempt.error_message": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PublicationAttempt.post"`)
	}
	return nil
}

func (_u *PublicationAttemptUpdateOne) sqlSave(ctx context.Context) (_node *PublicationAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(publicationattempt.Table, publicationattempt.Columns, sqlgraph.NewFieldSpec(publicationattempt.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PublicationAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicationattempt.FieldID)
		for _, f := range fields {
			if !publicationattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != publicationattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(publicationattempt.FieldOutcome, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Retryable(); ok {
		_spec.SetField(publicationattempt.FieldRetryable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(publicationattempt.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(publicationattempt.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(publicationattempt.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(publicationattempt.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(publicationattempt.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(publicationattempt.FieldFinishedAt, field.TypeTime)
	}
	_node = &PublicationAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publicationattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
