// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Godspower-Eze/infoai-backend/ent/post"
	"github.com/Godspower-Eze/infoai-backend/ent/publicationattempt"
	"github.com/google/uuid"
)

// PublicationAttempt is the model entity for the PublicationAttempt schema.
type PublicationAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AttemptNumber holds the value of the "attempt_number" field.
	AttemptNumber int `json:"attempt_number,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID uuid.UUID `json:"post_id,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger publicationattempt.Trigger `json:"trigger,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome publicationattempt.Outcome `json:"outcome,omitempty"`
	// Retryable holds the value of the "retryable" field.
	Retryable bool `json:"retryable,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PublicationAttemptQuery when eager-loading is set.
	Edges        PublicationAttemptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PublicationAttemptEdges holds the relations/edges for other nodes in the graph.
type PublicationAttemptEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PublicationAttemptEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PublicationAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case publicationattempt.FieldRetryable:
			values[i] = new(sql.NullBool)
		case publicationattempt.FieldAttemptNumber:
			values[i] = new(sql.NullInt64)
		case publicationattempt.FieldTrigger, publicationattempt.FieldOutcome, publicationattempt.FieldErrorCode, publicationattempt.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case publicationattempt.FieldStartedAt, publicationattempt.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		case publicationattempt.FieldID, publicationattempt.FieldPostID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PublicationAttempt fields.
func (_m *PublicationAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case publicationattempt.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case publicationattempt.FieldAttemptNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_number", values[i])
			} else if value.Valid {
				_m.AttemptNumber = int(value.Int64)
			}
		case publicationattempt.FieldPostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value != nil {
				_m.PostID = *value
			}
		case publicationattempt.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = publicationattempt.Trigger(value.String)
			}
		case publicationattempt.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = publicationattempt.Outcome(value.String)
			}
		case publicationattempt.FieldRetryable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field retryable", values[i])
			} else if value.Valid {
				_m.Retryable = value.Bool
			}
		case publicationattempt.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case publicationattempt.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case publicationattempt.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case publicationattempt.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PublicationAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *PublicationAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PublicationAttempt entity.
func (_m *PublicationAttempt) QueryPost() *PostQuery {
	return NewPublicationAttemptClient(_m.config).QueryPost(_m)
}

// Update returns a builder for updating this PublicationAttempt.
// Note that you need to call PublicationAttempt.Unwrap() before calling this method if this PublicationAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PublicationAttempt) Update() *PublicationAttemptUpdateOne {
	return NewPublicationAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PublicationAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PublicationAttempt) Unwrap() *PublicationAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PublicationAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PublicationAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("PublicationAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("attempt_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNumber))
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(fmt.Sprintf("%v", _m.Trigger))
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outcome))
	builder.WriteString(", ")
	builder.WriteString("retryable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retryable))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PublicationAttempts is a parsable slice of PublicationAttempt.
type PublicationAttempts []*PublicationAttempt
