// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/godspowere/infoai-backend/ent/schema"
	"github.com/godspowere/infoai-backend/ent/user"
	"github.com/godspowere/infoai-backend/ent/xaccount"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	xaccountFields := schema.XAccount{}.Fields()
	_ = xaccountFields
	// xaccountDescXUserID is the schema descriptor for x_user_id field.
	xaccountDescXUserID := xaccountFields[1].Descriptor()
	// xaccount.XUserIDValidator is a validator for the "x_user_id" field. It is called by the builders before save.
	xaccount.XUserIDValidator = xaccountDescXUserID.Validators[0].(func(string) error)
	// xaccountDescUsername is the schema descriptor for username field.
	xaccountDescUsername := xaccountFields[2].Descriptor()
	// xaccount.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	xaccount.UsernameValidator = xaccountDescUsername.Validators[0].(func(string) error)
	// xaccountDescDisplayName is the schema descriptor for display_name field.
	xaccountDescDisplayName := xaccountFields[3].Descriptor()
	// xaccount.DefaultDisplayName holds the default value on creation for the display_name field.
	xaccount.DefaultDisplayName = xaccountDescDisplayName.Default.(string)
	// xaccountDescScopes is the schema descriptor for scopes field.
	xaccountDescScopes := xaccountFields[8].Descriptor()
	// xaccount.DefaultScopes holds the default value on creation for the scopes field.
	xaccount.DefaultScopes = xaccountDescScopes.Default.([]string)
	// xaccountDescCreatedAt is the schema descriptor for created_at field.
	xaccountDescCreatedAt := xaccountFields[9].Descriptor()
	// xaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	xaccount.DefaultCreatedAt = xaccountDescCreatedAt.Default.(func() time.Time)
	// xaccountDescUpdatedAt is the schema descriptor for updated_at field.
	xaccountDescUpdatedAt := xaccountFields[10].Descriptor()
	// xaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	xaccount.DefaultUpdatedAt = xaccountDescUpdatedAt.Default.(func() time.Time)
	// xaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	xaccount.UpdateDefaultUpdatedAt = xaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// xaccountDescID is the schema descriptor for id field.
	xaccountDescID := xaccountFields[0].Descriptor()
	// xaccount.DefaultID holds the default value on creation for the id field.
	xaccount.DefaultID = xaccountDescID.Default.(func() uuid.UUID)
}
