// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/godspowere/infoai-backend/ent/predicate"
	"github.com/godspowere/infoai-backend/ent/scssession"
)

// SCSSessionUpdate is the builder for updating SCSSession entities.
type SCSSessionUpdate struct {
	config
	hooks    []Hook
	mutation *SCSSessionMutation
}

// Where appends a list predicates to the SCSSessionUpdate builder.
func (_u *SCSSessionUpdate) Where(ps ...predicate.SCSSession) *SCSSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetData sets the "data" field.
func (_u *SCSSessionUpdate) SetData(v []byte) *SCSSessionUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *SCSSessionUpdate) SetExpiry(v time.Time) *SCSSessionUpdate {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *SCSSessionUpdate) SetNillableExpiry(v *time.Time) *SCSSessionUpdate {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// Mutation returns the SCSSessionMutation object of the builder.
func (_u *SCSSessionUpdate) Mutation() *SCSSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SCSSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SCSSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SCSSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SCSSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SCSSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(scssession.Table, scssession.Columns, sqlgraph.NewFieldSpec(scssession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(scssession.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(scssession.FieldExpiry, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scssession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SCSSessionUpdateOne is the builder for updating a single SCSSession entity.
type SCSSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SCSSessionMutation
}

// SetData sets the "data" field.
func (_u *SCSSessionUpdateOne) SetData(v []byte) *SCSSessionUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *SCSSessionUpdateOne) SetExpiry(v time.Time) *SCSSessionUpdateOne {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *SCSSessionUpdateOne) SetNillableExpiry(v *time.Time) *SCSSessionUpdateOne {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// Mutation returns the SCSSessionMutation object of the builder.
func (_u *SCSSessionUpdateOne) Mutation() *SCSSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SCSSessionUpdate builder.
func (_u *SCSSessionUpdateOne) Where(ps ...predicate.SCSSession) *SCSSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SCSSessionUpdateOne) Select(field string, fields ...string) *SCSSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SCSSession entity.
func (_u *SCSSessionUpdateOne) Save(ctx context.Context) (*SCSSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SCSSessionUpdateOne) SaveX(ctx context.Context) *SCSSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SCSSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SCSSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SCSSessionUpdateOne) sqlSave(ctx context.Context) (_node *SCSSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(scssession.Table, scssession.Columns, sqlgraph.NewFieldSpec(scssession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SCSSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scssession.FieldID)
		for _, f := range fields {
			if !scssession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scssession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(scssession.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(scssession.FieldExpiry, field.TypeTime, value)
	}
	_node = &SCSSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scssession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
