// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/storagedeletion"
	"github.com/google/uuid"
)

// StorageDeletionCreate is the builder for creating a StorageDeletion entity.
type StorageDeletionCreate struct {
	config
	mutation *StorageDeletionMutation
	hooks    []Hook
}

// SetStorageKey sets the "storage_key" field.
func (_c *StorageDeletionCreate) SetStorageKey(v string) *StorageDeletionCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *StorageDeletionCreate) SetAttemptCount(v int) *StorageDeletionCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableAttemptCount(v *int) *StorageDeletionCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *StorageDeletionCreate) SetNextAttemptAt(v time.Time) *StorageDeletionCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableNextAttemptAt(v *time.Time) *StorageDeletionCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *StorageDeletionCreate) SetLastErrorCode(v string) *StorageDeletionCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableLastErrorCode(v *string) *StorageDeletionCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_c *StorageDeletionCreate) SetLastErrorMessage(v string) *StorageDeletionCreate {
	_c.mutation.SetLastErrorMessage(v)
	return _c
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableLastErrorMessage(v *string) *StorageDeletionCreate {
	if v != nil {
		_c.SetLastErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StorageDeletionCreate) SetCreatedAt(v time.Time) *StorageDeletionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableCreatedAt(v *time.Time) *StorageDeletionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StorageDeletionCreate) SetUpdatedAt(v time.Time) *StorageDeletionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableUpdatedAt(v *time.Time) *StorageDeletionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StorageDeletionCreate) SetID(v uuid.UUID) *StorageDeletionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StorageDeletionCreate) SetNillableID(v *uuid.UUID) *StorageDeletionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StorageDeletionMutation object of the builder.
func (_c *StorageDeletionCreate) Mutation() *StorageDeletionMutation {
	return _c.mutation
}

// Save creates the StorageDeletion in the database.
func (_c *StorageDeletionCreate) Save(ctx context.Context) (*StorageDeletion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageDeletionCreate) SaveX(ctx context.Context) *StorageDeletion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageDeletionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageDeletionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StorageDeletionCreate) defaults() {
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := storagedeletion.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := storagedeletion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := storagedeletion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := storagedeletion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageDeletionCreate) check() error {
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "StorageDeletion.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := storagedeletion.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "StorageDeletion.attempt_count"`)}
	}
	if v, ok := _c.mutation.AttemptCount(); ok {
		if err := storagedeletion.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.attempt_count": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastErrorCode(); ok {
		if err := storagedeletion.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.last_error_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastErrorMessage(); ok {
		if err := storagedeletion.LastErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "last_error_message", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.last_error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StorageDeletion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StorageDeletion.updated_at"`)}
	}
	return nil
}

func (_c *StorageDeletionCreate) sqlSave(ctx context.Context) (*StorageDeletion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageDeletionCreate) createSpec() (*StorageDeletion, *sqlgraph.CreateSpec) {
	var (
		_node = &StorageDeletion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storagedeletion.Table, sqlgraph.NewFieldSpec(storagedeletion.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(storagedeletion.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(storagedeletion.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = &value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(storagedeletion.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = &value
	}
	if value, ok := _c.mutation.LastErrorMessage(); ok {
		_spec.SetField(storagedeletion.FieldLastErrorMessage, field.TypeString, value)
		_node.LastErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(storagedeletion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(storagedeletion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// StorageDeletionCreateBulk is the builder for creating many StorageDeletion entities in bulk.
type StorageDeletionCreateBulk struct {
	config
	err      error
	builders []*StorageDeletionCreate
}

// Save creates the StorageDeletion entities in the database.
func (_c *StorageDeletionCreateBulk) Save(ctx context.Context) ([]*StorageDeletion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StorageDeletion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageDeletionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageDeletionCreateBulk) SaveX(ctx context.Context) []*StorageDeletion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageDeletionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageDeletionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
