// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/predicate"
	"github.com/Godspower-Eze/infoai-backend/ent/storagedeletion"
)

// StorageDeletionUpdate is the builder for updating StorageDeletion entities.
type StorageDeletionUpdate struct {
	config
	hooks    []Hook
	mutation *StorageDeletionMutation
}

// Where appends a list predicates to the StorageDeletionUpdate builder.
func (_u *StorageDeletionUpdate) Where(ps ...predicate.StorageDeletion) *StorageDeletionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *StorageDeletionUpdate) SetAttemptCount(v int) *StorageDeletionUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableAttemptCount(v *int) *StorageDeletionUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *StorageDeletionUpdate) AddAttemptCount(v int) *StorageDeletionUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *StorageDeletionUpdate) SetNextAttemptAt(v time.Time) *StorageDeletionUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableNextAttemptAt(v *time.Time) *StorageDeletionUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *StorageDeletionUpdate) ClearNextAttemptAt() *StorageDeletionUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *StorageDeletionUpdate) SetLastErrorCode(v string) *StorageDeletionUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableLastErrorCode(v *string) *StorageDeletionUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *StorageDeletionUpdate) ClearLastErrorCode() *StorageDeletionUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *StorageDeletionUpdate) SetLastErrorMessage(v string) *StorageDeletionUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *StorageDeletionUpdate) SetNillableLastErrorMessage(v *string) *StorageDeletionUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *StorageDeletionUpdate) ClearLastErrorMessage() *StorageDeletionUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StorageDeletionUpdate) SetUpdatedAt(v time.Time) *StorageDeletionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StorageDeletionMutation object of the builder.
func (_u *StorageDeletionUpdate) Mutation() *StorageDeletionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StorageDeletionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageDeletionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StorageDeletionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageDeletionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StorageDeletionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storagedeletion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageDeletionUpdate) check() error {
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := storagedeletion.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := storagedeletion.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.last_error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorMessage(); ok {
		if err := storagedeletion.LastErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "last_error_message", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.last_error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageDeletionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagedeletion.Table, storagedeletion.Columns, sqlgraph.NewFieldSpec(storagedeletion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(storagedeletion.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(storagedeletion.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(storagedeletion.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(storagedeletion.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(storagedeletion.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(storagedeletion.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storagedeletion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagedeletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StorageDeletionUpdateOne is the builder for updating a single StorageDeletion entity.
type StorageDeletionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageDeletionMutation
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *StorageDeletionUpdateOne) SetAttemptCount(v int) *StorageDeletionUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableAttemptCount(v *int) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *StorageDeletionUpdateOne) AddAttemptCount(v int) *StorageDeletionUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *StorageDeletionUpdateOne) SetNextAttemptAt(v time.Time) *StorageDeletionUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableNextAttemptAt(v *time.Time) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *StorageDeletionUpdateOne) ClearNextAttemptAt() *StorageDeletionUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *StorageDeletionUpdateOne) SetLastErrorCode(v string) *StorageDeletionUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableLastErrorCode(v *string) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *StorageDeletionUpdateOne) ClearLastErrorCode() *StorageDeletionUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *StorageDeletionUpdateOne) SetLastErrorMessage(v string) *StorageDeletionUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *StorageDeletionUpdateOne) SetNillableLastErrorMessage(v *string) *StorageDeletionUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *StorageDeletionUpdateOne) ClearLastErrorMessage() *StorageDeletionUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StorageDeletionUpdateOne) SetUpdatedAt(v time.Time) *StorageDeletionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StorageDeletionMutation object of the builder.
func (_u *StorageDeletionUpdateOne) Mutation() *StorageDeletionMutation {
	return _u.mutation
}

// Where appends a list predicates to the StorageDeletionUpdate builder.
func (_u *StorageDeletionUpdateOne) Where(ps ...predicate.StorageDeletion) *StorageDeletionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StorageDeletionUpdateOne) Select(field string, fields ...string) *StorageDeletionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StorageDeletion entity.
func (_u *StorageDeletionUpdateOne) Save(ctx context.Context) (*StorageDeletion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StorageDeletionUpdateOne) SaveX(ctx context.Context) *StorageDeletion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StorageDeletionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StorageDeletionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StorageDeletionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storagedeletion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StorageDeletionUpdateOne) check() error {
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := storagedeletion.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.attempt_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := storagedeletion.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.last_error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorMessage(); ok {
		if err := storagedeletion.LastErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "last_error_message", err: fmt.Errorf(`ent: validator failed for field "StorageDeletion.last_error_message": %w`, err)}
		}
	}
	return nil
}

func (_u *StorageDeletionUpdateOne) sqlSave(ctx context.Context) (_node *StorageDeletion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storagedeletion.Table, storagedeletion.Columns, sqlgraph.NewFieldSpec(storagedeletion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StorageDeletion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storagedeletion.FieldID)
		for _, f := range fields {
			if !storagedeletion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storagedeletion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(storagedeletion.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(storagedeletion.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(storagedeletion.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(storagedeletion.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(storagedeletion.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(storagedeletion.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(storagedeletion.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storagedeletion.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &StorageDeletion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storagedeletion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
