// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Godspower-Eze/infoai-backend/ent/user"
	"github.com/Godspower-Eze/infoai-backend/ent/xaccount"
	"github.com/google/uuid"
)

// XAccount is the model entity for the XAccount schema.
type XAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// XUserID holds the value of the "x_user_id" field.
	XUserID string `json:"x_user_id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// ProfileImageURL holds the value of the "profile_image_url" field.
	ProfileImageURL *string `json:"profile_image_url,omitempty"`
	// SubscriptionType holds the value of the "subscription_type" field.
	SubscriptionType string `json:"subscription_type,omitempty"`
	// SubscriptionCheckedAt holds the value of the "subscription_checked_at" field.
	SubscriptionCheckedAt *time.Time `json:"subscription_checked_at,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken []byte `json:"-"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken *[]byte `json:"-"`
	// TokenExpiry holds the value of the "token_expiry" field.
	TokenExpiry time.Time `json:"token_expiry,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// RateLimitRemaining holds the value of the "rate_limit_remaining" field.
	RateLimitRemaining *int `json:"rate_limit_remaining,omitempty"`
	// RateLimitResetAt holds the value of the "rate_limit_reset_at" field.
	RateLimitResetAt *time.Time `json:"rate_limit_reset_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the XAccountQuery when eager-loading is set.
	Edges           XAccountEdges `json:"edges"`
	user_x_accounts *uuid.UUID
	selectValues    sql.SelectValues
}

// XAccountEdges holds the relations/edges for other nodes in the graph.
type XAccountEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Posts holds the value of the posts edge.
	Posts []*Post `json:"posts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e XAccountEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// PostsOrErr returns the Posts value or an error if the edge
// was not loaded in eager-loading.
func (e XAccountEdges) PostsOrErr() ([]*Post, error) {
	if e.loadedTypes[1] {
		return e.Posts, nil
	}
	return nil, &NotLoadedError{edge: "posts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*XAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case xaccount.FieldAccessToken, xaccount.FieldRefreshToken, xaccount.FieldScopes:
			values[i] = new([]byte)
		case xaccount.FieldRateLimitRemaining:
			values[i] = new(sql.NullInt64)
		case xaccount.FieldXUserID, xaccount.FieldUsername, xaccount.FieldDisplayName, xaccount.FieldProfileImageURL, xaccount.FieldSubscriptionType:
			values[i] = new(sql.NullString)
		case xaccount.FieldSubscriptionCheckedAt, xaccount.FieldTokenExpiry, xaccount.FieldRateLimitResetAt, xaccount.FieldCreatedAt, xaccount.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case xaccount.FieldID:
			values[i] = new(uuid.UUID)
		case xaccount.ForeignKeys[0]: // user_x_accounts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the XAccount fields.
func (_m *XAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case xaccount.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case xaccount.FieldXUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field x_user_id", values[i])
			} else if value.Valid {
				_m.XUserID = value.String
			}
		case xaccount.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case xaccount.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case xaccount.FieldProfileImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_image_url", values[i])
			} else if value.Valid {
				_m.ProfileImageURL = new(string)
				*_m.ProfileImageURL = value.String
			}
		case xaccount.FieldSubscriptionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_type", values[i])
			} else if value.Valid {
				_m.SubscriptionType = value.String
			}
		case xaccount.FieldSubscriptionCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_checked_at", values[i])
			} else if value.Valid {
				_m.SubscriptionCheckedAt = new(time.Time)
				*_m.SubscriptionCheckedAt = value.Time
			}
		case xaccount.FieldAccessToken:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value != nil {
				_m.AccessToken = *value
			}
		case xaccount.FieldRefreshToken:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value != nil {
				_m.RefreshToken = value
			}
		case xaccount.FieldTokenExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_expiry", values[i])
			} else if value.Valid {
				_m.TokenExpiry = value.Time
			}
		case xaccount.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case xaccount.FieldRateLimitRemaining:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_remaining", values[i])
			} else if value.Valid {
				_m.RateLimitRemaining = new(int)
				*_m.RateLimitRemaining = int(value.Int64)
			}
		case xaccount.FieldRateLimitResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_reset_at", values[i])
			} else if value.Valid {
				_m.RateLimitResetAt = new(time.Time)
				*_m.RateLimitResetAt = value.Time
			}
		case xaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case xaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case xaccount.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_x_accounts", values[i])
			} else if value.Valid {
				_m.user_x_accounts = new(uuid.UUID)
				*_m.user_x_accounts = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the XAccount.
// This includes values selected through modifiers, order, etc.
func (_m *XAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the XAccount entity.
func (_m *XAccount) QueryOwner() *UserQuery {
	return NewXAccountClient(_m.config).QueryOwner(_m)
}

// QueryPosts queries the "posts" edge of the XAccount entity.
func (_m *XAccount) QueryPosts() *PostQuery {
	return NewXAccountClient(_m.config).QueryPosts(_m)
}

// Update returns a builder for updating this XAccount.
// Note that you need to call XAccount.Unwrap() before calling this method if this XAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *XAccount) Update() *XAccountUpdateOne {
	return NewXAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the XAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *XAccount) Unwrap() *XAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: XAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *XAccount) String() string {
	var builder strings.Builder
	builder.WriteString("XAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("x_user_id=")
	builder.WriteString(_m.XUserID)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	if v := _m.ProfileImageURL; v != nil {
		builder.WriteString("profile_image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("subscription_type=")
	builder.WriteString(_m.SubscriptionType)
	builder.WriteString(", ")
	if v := _m.SubscriptionCheckedAt; v != nil {
		builder.WriteString("subscription_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("access_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("token_expiry=")
	builder.WriteString(_m.TokenExpiry.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	if v := _m.RateLimitRemaining; v != nil {
		builder.WriteString("rate_limit_remaining=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RateLimitResetAt; v != nil {
		builder.WriteString("rate_limit_reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// XAccounts is a parsable slice of XAccount.
type XAccounts []*XAccount
