// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Godspower-Eze/infoai-backend/ent/predicate"
	"github.com/Godspower-Eze/infoai-backend/ent/xaccount"
)

// XAccountUpdate is the builder for updating XAccount entities.
type XAccountUpdate struct {
	config
	hooks    []Hook
	mutation *XAccountMutation
}

// Where appends a list predicates to the XAccountUpdate builder.
func (_u *XAccountUpdate) Where(ps ...predicate.XAccount) *XAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *XAccountUpdate) SetUsername(v string) *XAccountUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *XAccountUpdate) SetNillableUsername(v *string) *XAccountUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *XAccountUpdate) SetDisplayName(v string) *XAccountUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *XAccountUpdate) SetNillableDisplayName(v *string) *XAccountUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProfileImageURL sets the "profile_image_url" field.
func (_u *XAccountUpdate) SetProfileImageURL(v string) *XAccountUpdate {
	_u.mutation.SetProfileImageURL(v)
	return _u
}

// SetNillableProfileImageURL sets the "profile_image_url" field if the given value is not nil.
func (_u *XAccountUpdate) SetNillableProfileImageURL(v *string) *XAccountUpdate {
	if v != nil {
		_u.SetProfileImageURL(*v)
	}
	return _u
}

// ClearProfileImageURL clears the value of the "profile_image_url" field.
func (_u *XAccountUpdate) ClearProfileImageURL() *XAccountUpdate {
	_u.mutation.ClearProfileImageURL()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *XAccountUpdate) SetAccessToken(v []byte) *XAccountUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *XAccountUpdate) SetRefreshToken(v []byte) *XAccountUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *XAccountUpdate) ClearRefreshToken() *XAccountUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *XAccountUpdate) SetTokenExpiry(v time.Time) *XAccountUpdate {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *XAccountUpdate) SetNillableTokenExpiry(v *time.Time) *XAccountUpdate {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *XAccountUpdate) SetScopes(v []string) *XAccountUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *XAccountUpdate) AppendScopes(v []string) *XAccountUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *XAccountUpdate) SetUpdatedAt(v time.Time) *XAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the XAccountMutation object of the builder.
func (_u *XAccountUpdate) Mutation() *XAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *XAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *XAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *XAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *XAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *XAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := xaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *XAccountUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := xaccount.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "XAccount.username": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "XAccount.owner"`)
	}
	return nil
}

func (_u *XAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(xaccount.Table, xaccount.Columns, sqlgraph.NewFieldSpec(xaccount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(xaccount.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(xaccount.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileImageURL(); ok {
		_spec.SetField(xaccount.FieldProfileImageURL, field.TypeString, value)
	}
	if _u.mutation.ProfileImageURLCleared() {
		_spec.ClearField(xaccount.FieldProfileImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(xaccount.FieldAccessToken, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(xaccount.FieldRefreshToken, field.TypeBytes, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(xaccount.FieldRefreshToken, field.TypeBytes)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(xaccount.FieldTokenExpiry, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(xaccount.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, xaccount.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(xaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{xaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// XAccountUpdateOne is the builder for updating a single XAccount entity.
type XAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *XAccountMutation
}

// SetUsername sets the "username" field.
func (_u *XAccountUpdateOne) SetUsername(v string) *XAccountUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *XAccountUpdateOne) SetNillableUsername(v *string) *XAccountUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *XAccountUpdateOne) SetDisplayName(v string) *XAccountUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *XAccountUpdateOne) SetNillableDisplayName(v *string) *XAccountUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProfileImageURL sets the "profile_image_url" field.
func (_u *XAccountUpdateOne) SetProfileImageURL(v string) *XAccountUpdateOne {
	_u.mutation.SetProfileImageURL(v)
	return _u
}

// SetNillableProfileImageURL sets the "profile_image_url" field if the given value is not nil.
func (_u *XAccountUpdateOne) SetNillableProfileImageURL(v *string) *XAccountUpdateOne {
	if v != nil {
		_u.SetProfileImageURL(*v)
	}
	return _u
}

// ClearProfileImageURL clears the value of the "profile_image_url" field.
func (_u *XAccountUpdateOne) ClearProfileImageURL() *XAccountUpdateOne {
	_u.mutation.ClearProfileImageURL()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *XAccountUpdateOne) SetAccessToken(v []byte) *XAccountUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *XAccountUpdateOne) SetRefreshToken(v []byte) *XAccountUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *XAccountUpdateOne) ClearRefreshToken() *XAccountUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *XAccountUpdateOne) SetTokenExpiry(v time.Time) *XAccountUpdateOne {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *XAccountUpdateOne) SetNillableTokenExpiry(v *time.Time) *XAccountUpdateOne {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *XAccountUpdateOne) SetScopes(v []string) *XAccountUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *XAccountUpdateOne) AppendScopes(v []string) *XAccountUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *XAccountUpdateOne) SetUpdatedAt(v time.Time) *XAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the XAccountMutation object of the builder.
func (_u *XAccountUpdateOne) Mutation() *XAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the XAccountUpdate builder.
func (_u *XAccountUpdateOne) Where(ps ...predicate.XAccount) *XAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *XAccountUpdateOne) Select(field string, fields ...string) *XAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated XAccount entity.
func (_u *XAccountUpdateOne) Save(ctx context.Context) (*XAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *XAccountUpdateOne) SaveX(ctx context.Context) *XAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *XAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *XAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *XAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := xaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *XAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := xaccount.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "XAccount.username": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "XAccount.owner"`)
	}
	return nil
}

func (_u *XAccountUpdateOne) sqlSave(ctx context.Context) (_node *XAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(xaccount.Table, xaccount.Columns, sqlgraph.NewFieldSpec(xaccount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "XAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, xaccount.FieldID)
		for _, f := range fields {
			if !xaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != xaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(xaccount.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(xaccount.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileImageURL(); ok {
		_spec.SetField(xaccount.FieldProfileImageURL, field.TypeString, value)
	}
	if _u.mutation.ProfileImageURLCleared() {
		_spec.ClearField(xaccount.FieldProfileImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(xaccount.FieldAccessToken, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(xaccount.FieldRefreshToken, field.TypeBytes, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(xaccount.FieldRefreshToken, field.TypeBytes)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(xaccount.FieldTokenExpiry, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(xaccount.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, xaccount.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(xaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &XAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{xaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
