// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SCSSession is the predicate function for scssession builders.
type SCSSession func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// XAccount is the predicate function for xaccount builders.
type XAccount func(*sql.Selector)
